unit_width = 44;
sluice_thickness = 2;
sluice_width = unit_width * 4 / 5;
sluice_height = sluice_width;
sluice_clearance = 0.5;
wall_thickness = 5;
sluice_retain = 2;
// Offset of the horn center of rotation;
horn_cor_offset = 5;
oring_dia = 0.5;
stem_dia = 8;
cup_height = 4;
